stages:
  - build
  - deploy

build:
  stage: build
  image: arctica/aws-node:latest
  script:
    - npm install
#    - npm run lint
#    - npm run test:js:coverage
    - npm run build
  artifacts:
    paths:
    - public/
    expire_in: 1 day

deploy-stage:
  stage: deploy
  image: arctica/aws-node:latest
  script:
    - npm install netlify-cli -g
    - netlify deploy -p public -s $NETLIFY_SITE -e deploy-preview -t $NETLIFY_TOKEN

  environment:
    name: Staging
    url: https://staging.davidbrookes.co.uk
  only:
  - develop

deploy-prod:
  stage: deploy
  image: arctica/aws-node:latest
  script:
    - npm install netlify-cli -g
    - netlify deploy -p public -s $NETLIFY_SITE -e production -t $NETLIFY_TOKEN
  environment:
    name: Production
    url: https://davidbrookes.co.uk
  only:
  - master
