stages:
  - build
  - deploy

test-unit:
  stage: build
  image: arctica/aws-node:latest
  script:
    - npm install
    - npm run test
    - npm run test:coverage

build:
  stage: build
  image: arctica/aws-node:latest
  script:
    - npm
    - npm run build
  artifacts:
    paths:
    - dist/
    expire_in: 1 day

deploy-stage:
  stage: deploy
  image: arctica/aws-node:latest
  script:
    - aws s3 sync --sse AES256 public/ s3://staging.davidbrookes.co.uk/ --cache-control max-age=604800 --delete && aws configure set preview.cloudfront true && aws cloudfront create-invalidation --distribution-id EIEJGUFROLIRM --paths "/*"
  environment:
    name: Staging
    url: https://staging.davidbrookes.co.uk
  only:
  - develop

deploy-prod:
  stage: deploy
  image: arctica/aws-node:latest
  script:
    - aws s3 sync --sse AES256 public/ s3://davidbrookes.co.uk/ --cache-control max-age=604800 --delete && aws configure set preview.cloudfront true && aws cloudfront create-invalidation --distribution-id EIEJGUFROLIRM --paths "/*"
  environment:
    name: Production
    url: https://davidbrookes.co.uk
  only:
  - master
