stages:
  - build
  - deploy

# test-unit:
#  stage: build
#  image: arctica/aws-node:latest
#  script:
#    - npm install
#    - npm run test:coverage

build:
  stage: build
  image: arctica/aws-node:latest
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
    - public/
    expire_in: 1 day

deploy-stage:
  stage: deploy
  image: arctica/aws-node:latest
  script:
    - "s3cmd sync public/ s3://staging.davidbrookes.co.uk
      --acl-public
      --delete-removed
      --guess-mime-type
      --no-preserve"
  environment:
    name: Staging
    url: https://staging.davidbrookes.co.uk
  only:
  - develop

deploy-prod:
  stage: deploy
  image: arctica/aws-node:latest
  script:
    - "s3cmd sync public/ s3://davidbrookes.co.uk
      --acl-public
      --delete-removed
      --guess-mime-type
      --no-mime-magic
      --no-preserve"
  environment:
    name: Production
    url: https://davidbrookes.co.uk
  only:
  - master
